<?php
/**
 * Copyright (C) $user$, Inc - All Rights Reserved
 *
 *  <other text>
 * @file        Job.php
 * @author      ignatenkovnikita
 * @date        $date$
 */

/**
 * Created by PhpStorm.
 * User: ignatenkovnikita
 * Web Site: http://IgnatenkovNikita.ru
 */

namespace ignatenkovnikita\queuemanager;


use yii\base\BaseObject;
use yii\base\InvalidConfigException;

class Job extends BaseObject
{
    public $name;

    public function init()
    {
        if (empty($this->name)) {
            throw new InvalidConfigException('Property name not empty, please set value');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

}