<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Report' => 'Отчет',
    'Statistics' => 'Статистика',
    'Enter date' => 'Укажите дату',
    'Are you sure to repeat this item?' => '',
    'Are you sure you want to delete this item?' => '',
    'Class' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Created At' => '',
    'Data' => '',
    'Delay' => '',
    'Delete' => '',
    'End Execute' => '',
    'ID' => '',
    'Name' => '',
    'Priority' => '',
    'Properties' => '',
    'Queue Managers' => '',
    'Repeat' => '',
    'Reset' => '',
    'Result' => '',
    'Result ID' => '',
    'Search' => '',
    'Sender' => '',
    'Start Execute' => '',
    'Status' => '',
    'Status Done' => '',
    'Status Error' => '',
    'Status Reserved' => '',
    'Status Waiting' => '',
    'Time Execute' => '',
    'Ttr' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
];
